### ISSUE TITLE
Plugin not loaded

### ISSUE THREAD

**Issue by SWarnberg** [dapplo/Dapplo.Microsoft.Extensions.Hosting#13]
Hi,

just found this exciting package and experimenting with it. However, I'm falling short because my Plugin is not loaded/executed. Anything wrong with this code. How can I know the reason why the plugin is not loaded?

```
public static IHostBuilder CreateHostBuilder(string[] args) =>
        Host.CreateDefaultBuilder(args)
	.UseWindowsService()
	.ConfigureServices((hostContext, services) =>
	{
		services.AddHostedService<FileSystemWorker>();
	})
	.ConfigurePlugins(builder =>
	{
		builder.AddScanDirectories(Path.Combine(Path.GetDirectoryName(typeof(Program).Assembly.Location), "PlugIns"));
		builder.IncludePlugins(@"**\*.Service.dll");
	});

```
The "FileSystemWorker" is loaded of course, but my runtime service in the "PlugIn" folder is never loaded, no matter what globs I pass to the builder.
The runtime service also has a public class that implements **IPlugin**.

**Comment by Lakritzator** [comment]
That is a mistake from my side, it's not correctly documented. 😞 

The code probably finds your plugin, but I assume it's only implementing IPlugin but not called "Plugin" or not in the right package.
If you look [here](https://github.com/dapplo/Dapplo.Microsoft.Extensions.Hosting/blob/master/src/Dapplo.Microsoft.Extensions.Hosting.Plugins/HostBuilderPluginExtensions.cs#L165), you can see that it tries to instantiate the type called AssemblyName.Plugin AND expect it to implement IPlugin (which you did).

I already have some experience with plug-in, add-ons, extensions or whatever you like to call it.
And some time ago I wrote a project for .NET Framework: https://github.com/dapplo/Dapplo.Addons, this was before there was a Hosting package, but had a similar approach.

The reason why it currently works like it does: I could have scanned the whole assembly for all the types implementing IPlugin but this doesn't make it faster.

I should have documented the fact that your type MUST be called Plugin AND inside a package with the same name as your assembly, besides it implementing IPlugin.

I think it would be good to provide options:

- By naming convention, that is the current behavior
- By type scanning, all IPlugin implementing types
- By providing your own function

Let me know if you get it working now you know the restriction. And maybe you like to tell me of you like the idea.

**Comment by Lakritzator** [comment]
With the most recent version, which I just build so it takes a few minutes before nuget makes them available, you should not have to change a single thing.

The link I've mentioned in a previous comment wont make sense anymore.

You can now specify which way is used, see the documentation, and by default you now just need to implement IPlugin on a public class... which you did.

**Comment by SWarnberg** [comment]
Sweet! Works like a charm.
Thanks.
