### ISSUE TITLE
Include .NET Framework support

### ISSUE THREAD

**Issue by JensYvanDeCraecker** [dapplo/Dapplo.Microsoft.Extensions.Hosting#22]
Hello

I have forked, built and tested your WinForms project succesfully in .NET Framework 4.7.2.
Is there any specific reason why this isn't yet supported?

**Comment by Lakritzator** [comment]
Hi,

good question!!! I didn't support .NET Framework as there were some challenges in the beginning, especially with the loading of plugins as this wouldn't work (new APIs in dotnet core).

And it was an experiment to see if this even makes sense...

I think you are right, it might work for some places so I will try to enable it where possible, maybe I even port the code in https://github.com/dapplo/Dapplo.Addons to work similar as the current plugin loading, so one should hardly notice a difference.

Best wishes,
Robin

**Comment by JensYvanDeCraecker** [comment]
The reason I still use .NET Framework for WinForms is because .NET Core only has a very tiny amount of controls supported and the designer is super slow and buggy.

Hopefully you can support Framework in the near future.

Maybe support the libraries that do work in Framework first (I guess that WPF will work too, not tested it yet). These are independent of your plugin library. And then try to support the other ones.

Have a nice day and keep up the good work!
Jens

**Comment by JensYvanDeCraecker** [comment]
If I have the time tomorrow. I will try to build the other libraries in .NET Framework as well.

**Comment by Lakritzator** [comment]
I've already started a branch, feature/net472, as expected the assembly loading needs work.

**Comment by Lakritzator** [comment]
I think the basics work now. The samples should work in the feature branch, with assembly loading and all. I would expect there to be an issue with dependencies inside a plugin, I didn't validate this yet.

I'm very tired, between work and having a 4yo around all day, who is also keeping me awake at night... So I call it a day, be free to look at it.

**Comment by Lakritzator** [comment]
I've just merged the changes, let me know this works for you.

**Comment by Lakritzator** [comment]
Thanks for the feedback.
