### ISSUE TITLE
LogLevel set in configuration is being ignored in Hosting.WinForms

### ISSUE THREAD

**Issue by ruffk** [dapplo/Dapplo.Microsoft.Extensions.Hosting#34]
Hi

I've created both a WinForm test application and also tested the included sample.  No matter what the configuration files are set to, the LogLevel minimums do not change and no filters are added.

Hostsettings.json is set to Development
appsettings.Development.json is getting loaded as I can get configuration values

However if LogLevel is set nothing changes.  I was trying to get debug level logging for the application code but can only get information level.  And changing the Microsoft category level has no effect either.

I assume in the solution that all the configuration .json files should be set to "copy if newer" to the output directory.

Thanks.

**Comment by ruffk** [comment]
Here is the fix.  It needs to be applied to applicable sample code.

        private static IHostBuilder ConfigureLogging(this IHostBuilder hostBuilder)
        {
            return hostBuilder.ConfigureLogging((hostContext, configLogging) =>
            {
                configLogging
                    .AddConfiguration(hostContext.Configuration.GetSection("Logging"))
                    .AddConsole()
                    .AddDebug();
            });
        }

**Comment by Lakritzator** [comment]
Good point, fixed it!

Thanks!
