### ISSUE TITLE
Caliburn.Micro 4.0 Release Support?

### ISSUE THREAD

**Issue by pjmagee** [dapplo/Dapplo.Microsoft.Extensions.Hosting#35]
System.IO.FileNotFoundException: 'Could not load file or assembly 'Caliburn.Micro, Version=3.2.0.0, Culture=neutral, PublicKeyToken=8e5891231f2ed21f'. The system cannot find the file specified.'

**Comment by pjmagee** [comment]
Looks like `CaliburnMicroWindowManager` just needs a quick update on making a few methods `Async` with `Task`.

**Comment by Lakritzator** [comment]
I did have a look at this a few weeks ago, but was facing one or two challenges.
The biggest issue was time, and I have a more urgent issue which is bugging me, I don't get a MapApps style applied to the application for some reason...

**Comment by pjmagee** [comment]
Okay, thanks for the reply. I'm currently looking at Maui - as this uses the same Hosting pattern as Microsoft.Extensions.Hosting from what it looks like.

**Comment by Lakritzator** [comment]
Actually I was confused, I have another repo called: https://github.com/dapplo/Dapplo.CaliburnMicro
There it would be quite complex to replace CalburnMicro, while is **way** more integrated.
That project provides a lot of building blocks for a desktop application, and offered components including dependency injection and addons, with a very biased way of working.

This project uses a lot of Microsofts extension hosting, and tries to stay out of the way. So you will need to bring a lot yourself, which is good to have options.

That means that here it "should" be a lot less work, to be honest I didn't check it out yet...

I will also look at Maui for some of my projects, and keep an eye out to try to make this similar in the experience you get.

**Comment by Lakritzator** [comment]
I just updated CaliburnMicro to version 4, and released the new packages.

I also tried to use the template I created, to get a quick start, via the following steps:

- `dotnet new -i Dapplo.Microsoft.Extensions.Hosting.CaliburnMicro.Template.CSharp`
- `dotnet new caliburnmicrohost`
- `dotnet run --framework net5.0-windows`

Looking good so far.

**Comment by Lakritzator** [comment]
I guess I should have closed this issue, with version 0.6.3 this is implemented.
