### ISSUE TITLE
Missing package description

### ISSUE THREAD

**Issue by mgnslndh** [dapplo/Dapplo.Microsoft.Extensions.Hosting#6]
Hi!

I added the `Dapplo.Microsoft.Extensions.Hosting.Wpf` package to a project and noticed that the package was missing a package description.

Would you like a PR that adds descriptions to the packages in this repo or is that something you want to handle on your own?

Thanks for an interesting NuGet package!

**Comment by Lakritzator** [comment]
PR's are always welcome, yes please!

Nice to hear someone is using it, can you give some feedback how it has been working for you?
I wanted to start using this for Greenshot but didn't have time yet to prepare the code for this.

**Comment by mgnslndh** [comment]
I'll have to get some hours working with the package before getting back to you on that. But it is definitely something I've been wanting to have for desktop since way back when the MVC/Owin used the Startup class to configure the application.

**Comment by mgnslndh** [comment]
I tried to fix the warnings about the deprecated use of <PackageIconUrl/> but it seems like no NuGet client supports showing the self contained icon. It was possible to embed the icon but I could not get Visual Studio or NuGet Explorer to show the icon. Perhaps it is better to keep the warnings until Visual Studio has better support.

**Comment by Lakritzator** [comment]
Yeah, this with the icon also annoyed me, as in the documentation there was no mentioning that one could use the .ico file. I'm not sure how it's currently done, if the icon itself is embedded or just a png, but ico files have multiple resolutions so this has some advantages!

Anyway, it's not an urgent issue. Thanks for the PR, it got merged and 0.3.4 should be on NuGet by the time you read this.

I'm keeping the issue open a bit longer, I want to know what you like and / or dislike about the packages.

**Comment by Lakritzator** [comment]
Maybe you have been using it for a while, maybe you abandoned it? I would be happy to hear any remarks you have about this project. Closing this issue anyway, but please do comment!
